# Generated by Django 5.2.8 on 2025-11-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
